name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11, 17, 21 ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: |
            ${{ matrix.java-version }}
            21

      # delete gradle.properties in Java 8 because it contains a then-unsupported JVM argument: --add-exports
      - run: rm gradle.properties
        if: ${{ matrix.java-version == 8 }}

      - run: ./gradlew assemble check --info
        env:
          JAVA_TOOLCHAIN: ${{ matrix.java-version }}
